### ISSUE TITLE
One commit ahead after I fork?

### ISSUE THREAD

**Issue by miquelduranfrigola** [ersilia-os/eos3mk2#1]
Hi @DhanshreeA
I have followed the normal procedure of model incorporation. As soon as I got the message in the issue, I forked the repository to miquelduranfrigola/eos3mk2. I worked on that fork but then, when trying to do the PR, I was one commit behind ersilia-os/eos3mk2 for some reason.
I haven't thought to much about it, but, to me, this looks as if there are actions that happen **after** we write the message to the user containing the model id and the model incorporation steps.
In my opinion, the message should be the last thing appearing. No changes in the ersilia-os/eos3mk2 repository can happen after the identifier is revealed to the user.
Do you agree?

**Comment by DhanshreeA** [comment]
This is very strange and shouldn't be happening. Let me try to repro this with the eos-demo.

**Comment by miquelduranfrigola** [comment]
We were not able to reproduce the error, so I close the issue
